name = "Twenty Twelve borkedLabs"
license = "GPL v2 or later"
licenselink = "http://www.gnu.org/licenses/gpl-2.0.html"
description = "Modified port of the wordpress 2012 theme"

[author]
    name = "Mark Roszko"
    homepage = "http://borkedlabs.com"

[original]
    author =  "wordpressdotorg"
    homepage = "https://wordpress.org/themes/twentytwelve/"